### ISSUE TITLE
Serve unsigned if `Accept` is unacceptable

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#109]
`Accept` request header should either be missing, contain `*/*`, or specify `b2` as one of the accepted versions.

**Comment by Gregable** [comment]
I thought `*/*` was not considered acceptable, at least currently. Unless of course it also contains `b2`.

**Comment by twifkak** [comment]
Hm, yeah, you're right. `*/*, application/signed-exchange;v=b2` should not cause the packager to respond with `b1` or `b3`.

**Comment by Gregable** [comment]
True, but that wasn't my point. My point was that:

`Accept: */*`

Should not return a b2 SXG currently. In the future once more useragents support signed exchanges, maybe it should, but for now that seems risky.

However, `Accept: */*, application/signed-exchange;v=b2` should return a b2 SXG.

**Comment by twifkak** [comment]
That part is currently solved by #103.

**Comment by Gregable** [comment]
SG
