### ISSUE TITLE
Perform light AMP validation

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#140]
Transforms may have unintended effects on invalid documents. There may be cases where the SXG is fetched and served by third parties without validation. Since full validation at serve time is too expensive, it should perform some light validation; at least to verify that the document intends to be AMP.

**Comment by Gregable** [comment]
Knowing the transforms that run, I doubt any of the transforms would make an invalid amp document particularly dangerous. Hard to guarantee that's the case, but most of them just exist to make the document *less* likely to behave in non-amp manners, such as executing javascript.

An additional idea would be to add a transformer that strips a handful of known disallowed HTML, such as extra attention to `script` tags and stripping `on*` attributes. These will be no-ops on amp pages, and so should be cheap to run.

**Comment by twifkak** [comment]
@Gregable's suggestion has been split into #148.
