### ISSUE TITLE
Serve v=b1 signed exchanges

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#15]
This is a tracking bug to make sure the AMP packager serves valid signed exchanges per the evolving v=b1 spec. Support for v=b0 would need to co-exist for a few months.

Spec changes being drafted here: https://github.com/WICG/webpackage/pull/232

At present, these Chromium changes seem relevant:

  - [ ] restrict :url scheme to https https://crrev.com/c/1114407
  - [ ] Apply scheme restriction to {cert,validity}-url https://crrev.com/c/1114403
  - [ ] Require CanSignHttpExchangesDraft cert extension https://crrev.com/c/1111485 (modulo https://github.com/WICG/webpackage/issues/238)
  - [ ] Add CT verification for Signed Exchange https://crrev.com/c/1056776
  - [ ] SignedExchange: Forbid RSA signatures https://crrev.com/c/1096578
  - [ ] Signed exchange: Check content-type of certificate chain https://crrev.com/c/1082175
  - [ ] Signed Exchange: Switch to b1 envelope format https://crrev.com/c/1081773
  - [ ] Update Signed Exchange's Signature header format to b1 https://crrev.com/c/1077111
  - [ ] Check the validity URL is same-origin with the request url https://crrev.com/c/1075833
  - [ ] Signed exchange: Drop b0 support https://crrev.com/c/1074670
  - [ ] Introduce SignedExchangePrologue, the prologue parser for the b1 format https://crrev.com/c/1075883
  - [ ] Don't handle signed exchange transferred over plain HTTP https://crrev.com/c/1074915
  - [ ] Add OCSP check for Signed Exchange https://crrev.com/c/1060933
  - [ ] SignedExchangeVerifier: Support ecdsa_secp256r1_sha256 signature algorithm. https://crrev.com/c/979377

(I may eventually split out bugs for larger subprojects, like OCSP stapling.)

See also http://b/92515679.

**Comment by Gregable** [comment]
Renamed to b2. Not sure if more todos need to be added.
