### ISSUE TITLE
`Vary` header sent twice

### ISSUE THREAD

**Issue by Gregable** [ampproject/amppackager#153]
```
$ curl 'https://azei-package-test.com/' -H 'Accept: text/html,application/signed-exchange;v=b2' -i | less
```

```
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 11 Oct 2018 21:08:33 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: max-age=1209600
Etag: W/"5ba29e16-ba7"
Expires: Thu, 25 Oct 2018 21:08:33 GMT
Last-Modified: Wed, 19 Sep 2018 19:05:58 GMT
Vary: Accept,AMP-Cache-Transform
Vary: Accept,AMP-Cache-Transform
```

This doesn't happen if the -H 'AMP-Cache-Transform: google' header is added, or if the Accept header doesn't include signed-exchange. However, this is what a browser that supports signed exchanges would receive, so it is a real use case.

**Comment by twifkak** [comment]
This is a bug in our nginx config on azei-package-test, not amppackager. Nginx doesn't support very advanced configuration, and this is the best I could do. It's an acceptable loss I think, but feel free to fix it!

**Comment by Gregable** [comment]
no worries.
