### ISSUE TITLE
Vendor caches.json

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#156]
Currently, the list of caches is hard-coded into [amp_cache_transform.go](../blob/master/packager/amp_cache_transform/amp_cache_transform.go). In the future, the list should come from its canonical source in [caches.json](https://github.com/ampproject/amphtml/blob/master/caches.json), vendored into this repo with a reasonable frequency, in order to meet [the spec requirement](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-transform.md#request-header).

This is dependent on b/117418067 to implement URL rewrites.

**Comment by twifkak** [comment]
This is trickier than I thought. Perhaps I'm overthinking it.

There seem to be two parts to this.

(1) Getting the latest version of `caches.json`. Options:

  * git submodules. Submodules are supported by [GitHub](https://blog.github.com/2016-02-01-working-with-submodules/). We can lock it to a commit hash and update manually, or just submodule at HEAD. The latter seems fine in our case, since it'll require a manual embed step anyway. [1]
  * Shell script or Go code that `wget`s the file from raw.githubusercontent.com.

(2) Embedding the contents into the binary (as Go doesn't support importing resource files from the GOPATH):

  * Some hacky script that outputs a `caches.go` file somewhere.
  * https://github.com/go-bindata/go-bindata
  * https://github.com/mjibson/esc
  * https://github.com/omeid/go-resources
  * https://github.com/gobuffalo/packr
  * https://github.com/GeertJohan/go.rice

All of these involve running some command to snapshot the file into a generated Go file and pushing the change to GitHub. Having to do this every month would be time-consuming. It could be possible to create some cloud service cronjob thingie that does this, with merge access to the repo (or have it mail PRs).

Alternatively, we could have `amppkg` curl the file from `raw.githubusercontent.com` at startup, and cache it like with rtv.go. The downside here is users would have to be okay with their server making period outgoing connections to a somewhat sketchy domain. Another alternative might be a semi-automated process that snapshots the file from GitHub to cdn.ampproject.org, with a review process.

[1] Submodules are also supported by [`go get`](https://github.com/golang/go/blob/7f3313133ee3e40515aa99d3618b8e5eafed42d6/src/cmd/go/internal/get/vcs.go#L147-L148), but since it doesn't do any content embedding, we'd need `amppkg` to read `$GOPATH/src/github.com/ampproject/amppackager/amphtml/caches.json` at startup. Depending on source being installed would be bad.

**Comment by honeybadgerdontcare** [comment]
caches.json could be merged with metadata since we're already fetching metadata and it's being served by the same source as v0.js.

https://cdn.ampproject.org/rtv/metadata would then be something like:
```
{
  "ampRuntimeVersion": "011810152207300",
  "ampCssUrl": "https://cdn.ampproject.org/rtv/011810152207300/v0.css",
  "caches": [
    {
      "id": "google",
      "name": "Google AMP Cache",
      "docs": "https://developers.google.com/amp/cache/",
      "cacheDomain": "cdn.ampproject.org",
      "updateCacheApiDomainSuffix": "cdn.ampproject.org",
      "thirdPartyFrameDomainSuffix": "ampproject.net"
    },
    {
      "id": "cloudflare",
      "name": "Cloudflare AMP Cache",
      "docs": "https://amp.cloudflare.com/",
      "cacheDomain": "cdn.cloudflare.com",
      "updateCacheApiDomainSuffix": "amp.cloudflare.com",
      "thirdPartyFrameDomainSuffix": "cloudflareamp.net"
    }
  ]},
  "canaryPercentage": "0.1"
}
```

**Comment by honeybadgerdontcare** [comment]
@twifkak 	Does it need to be a cronjob or can it be a part of the normal AMP v0.js release process? If it's part of the release process then there's a known expectation of when the changes will roll out rather than at some time the cronjob runs.

**Comment by twifkak** [comment]
@honeybadgerdontcare That is a much better idea.

**Comment by twifkak** [comment]
We should add a presubmit to amphtml that verifies caches.json is valid JSON and contains at least ['google', 'cloudflare'] ids.

**Comment by jridgewell** [comment]
If we do this, we should probably move the the `metadata` endpoint to be outside the `/rtv/` directory. It's more of a "amp metadata" than an "rtv metadata" at that point.

Nit: I don't see the issue with making two requests?

**Comment by honeybadgerdontcare** [comment]
cl/220124822 keeps cdn.ampproject.org/caches.json in sync with the github repository version of caches.json and the amp packager can now rely on cdn.ampproject.org/caches.json to have the latest list of caches.

**Comment by twifkak** [comment]
It's been a long time since I've looked at this bug, but I think this is fixed per https://github.com/ampproject/amppackager/issues/156#issuecomment-436361057.

#199 should include fetching from cdn.ampproject.org/caches.json, with a fallback on google if fetch fails.
