### ISSUE TITLE
Document the need to update the packager binary

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#169]
Along with the rolling transformer versions comes the need to update the packager every so often. Once we decide on a process (e.g. whether to have a separate development branch, how old versions may be), we should update the Productionizing section of the readme to say what needs to be done.

**Comment by twifkak** [comment]
(Windy ramble ahead. Recommendation in last paragraph.)

We'd talked about doing our development on a `next` or `dev` branch and then snapshotting to master as part of the release process. An alternative: http://gopkg.in/

When you do `go get gopkg.in/foo/bar` it creates a go module in $GOPATH/src/gopkg.in/foo/bar that is a clone of github.com/foo/bar, where all the imports have been rewritten to point to itself. But if you do `go get gopkg.in/foo/bar.v1`, it'll create a clone of github.com/foo/bar at tag `v1.*`. (See gopkg.in for details.)

This would let us keep developing on master, and just create a new `v1.X` tag when releasing.

Apparently support for this is [hard-coded into go](https://github.com/golang/go/search?q=gopkg.in&unscoped_q=gopkg.in) as a bit of a legacy case; but perhaps it's here to stay?

The downside is it introduces another org (gopkg.in) that users would have to trust. Perhaps this further motivates the idea of publishing some checksums on ampproject.org? Though we'd have to reproduce the import-statement rewrites in order for that checksum to be valid.

Alternatively, maybe `go get -u` is just for development, and production requires checking out a specific tag or branch with `git`. The more that I think about it, the more that I like this approach.

**Comment by twifkak** [comment]
OK, gopkg.in doesn't have any SLAs: https://www.reddit.com/r/golang/comments/69qmc8/why_gopkgin_hasnt_caught_on/dhabmow

Further cements my recommendation that we update the instructions to say `git clone -b release github.com/ampproject/amppackager && cetera` and then our release process includes updating the `release` branch.

This doesn't help people using the transforms as a library, where as the "develop on `next`" strategy would. But then our goal is that all changes to the transformer are gated by an `if version >=` so there's soft protection there. And it's safe to assume that downstream dependents of the library will have their own release processes.

WDYT?

**Comment by alin04** [comment]
Here's one branching model we could adopt: https://nvie.com/posts/a-successful-git-branching-model/

**Comment by twifkak** [comment]
That's a nice thorough write-up (and diagram) of the "develop on `next`" strategy. I see that it has advantages:
 - Can continue developing on the `develop` branch while pushing hotfixes on the release branch.
 - We can also simplify the model by not doing a release branch (unless the need for a hotfix comes up).
 - `master` is the known-good copy of the code, which eases use for binary and library users.

It had some disadvantages too:
 - We'd probably mess up a lot by accidentally committing things to `master` instead of `develop`. (e.g. people would submit PRs to master because that's the way things are usually done)
 - The "full" code would be hidden behind some branch that most people browsing wouldn't notice.

But I just discovered we can configure that: https://help.github.com/articles/setting-the-default-branch/

So I'm more amenable to this now.

**Comment by twifkak** [comment]
OK, changed the default branch to `develop` per https://help.github.com/en/articles/setting-the-default-branch, and made both `develop` and `master` protected branches. I believe the automatic "Sync from Google" PRs will pick up this default, too.

It'd be nice to add more protections to `master` to prevent accidental merges there, like, requiring an "This is a release commit" comment or something.

It remains to document this in README.md and CONTRIBUTING.md.

**Comment by twifkak** [comment]
OK, this didn't work. Setting the default branch in GitHub also sets the default branch in git, which determines what gets downloaded by `go get`. I got rid of the `develop` branch, changed the default to a new `releases` branch, and will update the instructions accordingly. It means we have to be a little more careful with PRs, since they'll be opened against `releases` by default.
