### ISSUE TITLE
cert is missing CanSignHttpExchanges extension

### ISSUE THREAD

**Issue by vockalimo** [ampproject/amppackager#201]
i has test local step done. 
so I want to test on production 

```
amppkg
2018/11/27 03:35:39 cert is missing CanSignHttpExchanges extension
```
hmm...  anyone can help me ? 
thanks

**Comment by twifkak** [comment]
Hi! Yes, for production you will need a new certificate using that extension. For security reasons, you cannot use your normal TLS cert. You can get a CanSignHttpExchanges cert from [DigiCert here](https://www.digicert.com/account/ietf/http-signed-exchange.php).

Let me know if this step doesn't work!
