### ISSUE TITLE
Strip additional content-encodings

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#243]
Per WICG/webpackage#390 chromium disallows any content-encodings in addition to mi-sha256-03. However, it appears that https://github.com/WICG/webpackage/blob/master/go/signedexchange/signedexchange.go doesn't remove any content-encoding values passed to it. `packager/signer/signer.go` should delete the content-encoding header from the response it sends to `signedexchange`. (I'm assuming that Go's http client decodes the response.)

**Comment by irori** [comment]
Currently Chromium ignores additional content-encodings, but I think unsupported encodings in Content-Encoding header should cause a fallback redirect (http://crbug.com/931055).
