### ISSUE TITLE
Modify cache headers

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#251]
There is a difference between Google AMP Cache's behavior and the cache semantics specified by SXG b3. In order to make amppackager work transparently for the same set of pages that AMP supports today, we'll need to modify `cache-control` response headers so that they meet SXG requirements. (Maybe add a flag to disable this, though users who publish AMP pages are probably already ok with the semantics.)

**Comment by Gregable** [comment]
I'm not sure I'm parsing this correctly. What response header do we need? Is this inner or outer headers?

**Comment by twifkak** [comment]
Inner headers. The requirement is set by WICG/webpackage#326. Last time I looked into this, the end result was we'd need to convert `private` and/or `no-store` into `max-age=0` (or maybe `s-maxage=0`). See http://go/amp-sxg-uncacheable for details.

**Comment by Gregable** [comment]
Understood, thanks.

**Comment by twifkak** [comment]
I'm also thinking the flag to disable this could be the increasingly misnamed `ErrorOnStatefulHeaders` param in the amppkg.toml file.

**Comment by twifkak** [comment]
Just to be extra safe against [over-signing](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#seccons-over-signing), I'll close this bug WAI. New `warning` header from the cache makes it easier for pubs to discover the cause of the error, if it occurs. We can revisit if somebody expresses a need, but maybe off by default.
