### ISSUE TITLE
expired cert at https://amppackageexample.com

### ISSUE THREAD

**Issue by ireinhart** [ampproject/amppackager#265]
Hello!

I try to run this https://github.com/ampproject/amppackager/tree/releases/docker instruction including the test case.

In the logs I see the following error:
2019/03/20 16:01:09 Error fetching: Get https://amppackageexample.com/: x509: certificate has expired or is not yet valid

At chrome I see "Bad gateway".

Issue is, that https://amppackageexample.com has a expired ssl certificate.

**Comment by twifkak** [comment]
Apologies! I renewed amppackageexample's TLS certificate (and hopefully fixed the certbot config so it won't expire again).

I'm still looking into the 502.

**Comment by twifkak** [comment]
Fixed.

**Comment by ireinhart** [comment]
Thanks!
