### ISSUE TITLE
AMP page headers

### ISSUE THREAD

**Issue by ireinhart** [ampproject/amppackager#275]
At https://github.com/ampproject/amppackager#productionizing at paragraph 4 you describe witch header the amp page should send.
But it is a bit unclear - for us. Means html page, that the canonical page should send the vary header, too?

At the moment we serving at our amp page this header:
`vary: Accept-Encoding, AMP-Cache-Transform`
Is that enough? Or we misunderstand something?

Best,
Ingo

**Comment by ithinkihaveacat** [comment]
You're correct: the canonical does not need to send that header, only the AMP (provided they are different, and served from different URLs).

You only need to send that vary response header if the content of the URL varies depending on request headers.

**Comment by ireinhart** [comment]
Thx, we fix it and now it works.
