### ISSUE TITLE
Reorganize directories to match standard go layout

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#28]
Follow the [Standard Go Project Layout](https://github.com/golang-standards/project-layout). That entails:

- moving the `.go` files from the root into `internal/pkg/`
- moving the fuzz tests into `test/`
- moving the example toml into `configs/`

and maybe some other stuff.

**Comment by alin04** [comment]
Propose segregating packager from transformer code, e.g.
packager/
transformer/
Or should they be verbs?
package/
transform/

**Comment by honeybadgerdontcare** [comment]
I'd go with what we plan on calling it in documentation, which most likely will be nouns not verbs.

**Comment by twifkak** [comment]
Nouns SGTM. I'm slightly in favor of dropping 'pkg' and just having the code be at `transformer/**/*.go` or `transformer/**/internal/*.go`. https://github.com/golang-standards/project-layout/tree/master/pkg admits it's not universally accepted anyway. None of the third party libs we have in `vendor/` do this. But that's not a strongly held opinion; thoughts?

Once `pkg` is renamed to `transformer`, it may be worth renaming `transformer/transformer` to `transformer/transformers`, and moving `transformer/transform/transform.go` up a level to `transformer/transformer.go`. So people looking at this directory for the first time may start in the right place. :)

**Comment by twifkak** [comment]
Still needs #88 (or equivalent).

**Comment by alin04** [comment]
Hmm, I'm still on the fence about noun vs verb. Both are applicable depending on the circumstance. E.g. go's html package has both: node.go, token.go (verbs). render.go, parse.go (verbs)

So, perhaps
  transform/transformers/...
  transform/transform.go 

Bikeshedding...  You can ignore me. :)
