### ISSUE TITLE
Link to SXG generator services from docs

### ISSUE THREAD

**Issue by twifkak** [ampproject/amppackager#337]
The docs should include a section with links to SXG generator services that may be used instead of amppackager. Probably a wiki page, linked from README.md, so it can be updated easily.

See also: ampproject/amp.dev#2769

**Comment by rudygalfi** [comment]
Any generator services should suggest themselves for this list, as we may not be aware of them all. One I am aware of is [Cloudflare](https://blog.cloudflare.com/announcing-amp-real-url/).
