### ISSUE TITLE
Docker image build broken on new release

### ISSUE THREAD

**Issue by FranGM** [ampproject/amppackager#387]
Hi,

The Dockerfile included in the latest release doesn't build cleanly. It expects to be able to run seedcache.sh which seems to have been removed in the move from `b1` to `b3` on testdata.

I assume this deletion was maybe an accident and that script should be readded?

**Comment by banaag** [comment]
+FranGM, the files have been updated and pushed to the release branch. Let us know if we can close the bug.

**Comment by FranGM** [comment]
Yep, that's perfect, thank you!
