### ISSUE TITLE
What is "Error parsing OCSP response: ocsp: error from server: unauthorized" means?

### ISSUE THREAD

**Issue by adjieguntoro-tokped** [ampproject/amppackager#398]
Hello,
Hope anyone can help to solve this.

I'm trying to run amppkg on production server, I got this error messages and also amppkg binary doesn't run properly.

```
2020/02/26 19:49:44 Updating cert if necessary
2020/02/26 19:49:44 Certfetcher is not set, skipping cert updates. Checking cert on disk if updated.
2020/02/26 19:49:44 Updating OCSP; none cached yet.
2020/02/26 19:49:44 Updating OCSP; none cached yet.
2020/02/26 19:49:44 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2020/02/26 19:49:44 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2020/02/26 19:49:45 Error parsing OCSP response: ocsp: error from server: unauthorized
2020/02/26 19:49:45 no response matching the supplied certificate
Error parsing OCSP response
github.com/ampproject/amppackager/packager/certcache.(*CertCache).isHealthy
```

best,
Adjie

**Comment by banaag** [comment]
Hi Adjie,

Thanks for reaching out. From the error messages you sent, it looks like you are using an existing certificate on disk for amppackager and that it's having problems using that certificate to contact the OCSP server.  Questions for you:
1. Did your amppackager certificate (the one you configured as 'CertFile' in amppkg.toml) expire recently? 
2. Could you confirm that the certificate you are using matches the domain you are using it for?
openssl x509 -in YOUR_CERT_FILENAME_HERE -text -noout

Thanks!

**Comment by adjieguntoro-tokped** [comment]
Hi @banaag,

So, could you tell me the action item that I need to do?

1. Actually, I'm trying to update the certificate with the new one.
2. Yes, it matches.

**Comment by banaag** [comment]
Hi @adjieguntoro-tokped,

What do you mean by "I'm trying to update the certificate with the new one"?  Did you get a new certificate from Digicert and start using that with amppackager? Or are you trying to use the ACME feature in amppackager to do this?  If you're trying to use ACME, based on the log files you sent, certificate autorenewal is not turned on (see: "Certfetcher is not set, skipping cert updates. Checking cert on disk if updated.") so certificate auto-renewal will not be done. If you're trying to use a new certificate from Digicert, make sure that the CSR (Certificate Signing Request) you generated for this certificate used the same private key you are using with amppackager.

**Comment by adjieguntoro-tokped** [comment]
Hi @banaag,

It seems like my certificate already working fine. I'm not sure what happened on that. But, really appreciate your help. Thanks man! you are the champ.

I will close this issue.
