### ISSUE TITLE
amppackager panics when URLSet.Fetch is specified and ?fetch= is not specified

### ISSUE THREAD

**Issue by Warashi** [ampproject/amppackager#405]
When `URLSet.Fetch` is specified in amppkg.toml and `?fetch=` is NOT specified in request, amppackager should return error but it panics now.
The cause may be lack of nil check in fetchURLMatches https://github.com/ampproject/amppackager/blob/cc38c5fad40fc603119a298700820b97a4f0c54f/packager/signer/validation.go#L98-L124

**Comment by twifkak** [comment]
Thanks for the report! Sorry for the delay. Fix is pending in #406.
