### ISSUE TITLE
The header 'link' for the signed exchange payload has an invalid value.

### ISSUE THREAD

**Issue by Moshe-ship** [ampproject/amppackager#486]
Hi Guys, I'm using AMP Plugin on WordPress site, and I am facing this new issue, 

The link: https://majana.blog/web-stories/%d8%ae%d8%b7%d9%88%d8%a7%d8%aa-%d8%b9%d9%85%d9%84-%d8%a8%d9%88%d8%af%d9%83%d8%a7%d8%b3%d8%aa/

Could you guide me through this?

**Comment by Moshe-ship** [comment]
I've checked the Dev tool and it shows this:

Uncaught Error: No ampdoc found for [object HTMLElement]

**Comment by twifkak** [comment]
Hi @Moshe-ship I think this is the wrong repo for your bug report. Please try filing on https://github.com/ampproject/amp-wp.
