### ISSUE TITLE
rtv support

### ISSUE THREAD

**Issue by alin04** [ampproject/amppackager#58]
Periodically (hourly?) poll to get the latest rtv (and css url), store in memory. 

Pass these values into the local transformer library for writing the correct rtv script and css.

**Comment by honeybadgerdontcare** [comment]
The cache will be 50 minutes so hourly may make sense. It also could be set by a flag/parameter for the publisher to decide.

What will the packager do if it's inaccessible?

**Comment by alin04** [comment]
Can it fall back to the previous value stored in memory? How long is rtv good for?

If there is no previous value, then the packager will not transform/sign/package anything and will simply pass through the origin AMP HTML. Until the next time the periodic rtv poll occurs, which if successful, then the packager can resume its normal mode of operation.

**Comment by honeybadgerdontcare** [comment]
Perhaps but we'll want a policy around it. RTVs are served with a 1 year cache lifetime.

**Comment by alin04** [comment]
We can also fail fast if the very first rtv poll fails, and the entire AMP Packager web server can fail to start. That guarantees that there is at least one initial value.

**Comment by alin04** [comment]
still not actually used by local transformation library
