### ISSUE TITLE
AMP signed exchange showing error  : Not packaging because computed max-age 666 places expiry in the past

### ISSUE THREAD

**Issue by virendra-rastogi** [ampproject/amppackager#623]
![Screenshot from 2022-03-09 19-51-51](https://user-images.githubusercontent.com/101269278/157460295-e48397ff-6737-4759-9f16-8ead3d925b19.png)
My amppkg is not able to signed my pages when I debugged the same I am getting one error in the error log "Not packaging because computed max-age 86400 places expiry in the past" 

Please suggest .

URL : https://m.timesofindia.com/city/dehradun/bjp-pacifies-upset-senior-leaders-dhami-takes-oath-as-11th-ukhand-cm/amp_articleshow/84121833.cms

After Reading Issue [https://github.com/ampproject/amppackager/issues/395](https://github.com/ampproject/amppackager/issues/395 )
and doc: https://amp.dev/documentation/examples/components/amp-script/?format=websites

I have tried  <amp-script max-age="172800"> and different combination with other values but the error is same just number is changing in the error message.

Like :

2022/03/09 20:37:04 Not packaging because computed max-age 666 places expiry in the past
2022/03/09 20:37:04 Not packaging because computed max-age 84600 places expiry in the past 
etc.

**Comment by sisidovski** [comment]
Hi @virendra-rastogi , I wonder if you tried changing the inline `<amp-script>` on the page to load a JavaScript from external src by using `src` attribute instead of `script` attribute. As [mentioned in README](https://github.com/ampproject/amppackager#amp-script), it seems that currently -1 day limitation exists for inlined amp-script.

**Comment by virendra-rastogi** [comment]
@sisidovski Thanks a lot for the Help It worked for me .

**Comment by virendra-rastogi** [comment]
I got the resolution and It worked for me after changes in <amp-script max-age it worked
